### ISSUE TITLE
Component documentation

### ISSUE THREAD

**Issue by ittchmh** [alryaz/hass-hekr-component#1]
Hello,
please explain how to use this HASS component

I have devTid, appTid and ctrlKey of my meter
How sensor config must look like?

Something like this?

```
sensor:
  - platform: hass-hekr-component
    name: dds238-4w-1
    host: 192.168.1.111
    port: 10000
    control_key: 390d************************5d9e
    application_id: ffffffff*******ffffffff*******00000000000me.hekr.hummingbird
    
```

Component not working - I got error:

> Platform error sensor.hass-hekr-component - cannot import name 'load_protocol_definition' from 'custom_components.hass-hekr-component.hekrapi.protocol' (/config/custom_components/hass-hekr-component/hekrapi/protocol.py)

Now my config look like this:

```
sensor:
  - platform: hass-hekr-component
    name: dds238-4w-1
    host: 192.168.1.111
    port: 10000
    device_id: ESP_2M_840D********
    control_key: 390d************************5d9e
    application_id: ffffffff*******ffffffff*******00000000000me.hekr.hummingbird
    protocol: power_meter
```

Same error!

Repository hekrapi @ c6d16c5 not available, so I use latest release of this repo https://github.com/alryaz/hekrapi-python

UPDATE:

With new component it started to work, having some errors:
```
2019-12-14 20:32:39 ERROR (MainThread) [custom_components.hekr.sensor] Error while updating data: heartbeat could not execute for device ESP_2M_840D8EB88E4C@ESP_B88E4C.local:10000
2019-12-14 20:32:39 ERROR (MainThread) [custom_components.hekr.sensor] Exception occurred during device update
Traceback (most recent call last):
  File "/config/custom_components/hekr/sensor.py", line 221, in async_update
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady
2019-12-14 20:32:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hekr/sensor.py", line 221, in async_update
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hekr/sensor.py", line 260, in async_update
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady

```

**Comment by alryaz** [comment]
Please, check the latest release 62eb30c456f317441248dea72638dbabe3a17f57.
Although I know it's been a while, the issue should be resolved because it had to do with synchronized requests being handled incorrectly before.
