### ISSUE TITLE
HA 2023.6.0b1

### ISSUE THREAD

**Issue by Telectroboy** [alryaz/hass-hekr-component#17]
With the new beta version of HA 2023.6.0b2

The sensor is not working anymore.
Logs give an issue

Logger: py.warnings
Source: runner.py:179
First occurred: 14:10:12 (4 occurrences)
Last logged: 14:11:10

/usr/local/lib/python3.11/asyncio/base_events.py:1923: RuntimeWarning: coroutine 'HekrEntity.handle_data_update' was never awaited handle = None # Needed to break cycles when an exception occurs.

I guess it is related to the new python 3.11 version!

No?

**Comment by Telectroboy** [comment]
```
2023-06-02 14:10:11.828 DEBUG (MainThread) [custom_components.hekr.hekr_data] No updates scheduled for command "queryData"
2023-06-02 14:10:12.457 DEBUG (MainThread) [custom_components.hekr.hekr_data] Received response (message ID: 2286927) from information command (action: devSend) with data: (<Command("reportData", 11, RECEIVE)>, {'current_1': 17.333, 'current_2': 0.0, 'current_3': 0.0, 'voltage_1': 244.9, 'voltage_2': 0.0, 'voltage_3': 0.0, 'total_reactive_power': -0.0463, 'reactive_power_1': -0.0463, 'reactive_power_2': 0.0, 'reactive_power_3': 0.0, 'total_active_power': -4.2436, 'active_power_1': -4.2436, 'active_power_2': 0.0, 'active_power_3': 0.0, 'total_power_factor': 0.999, 'power_factor_1': 0.999, 'power_factor_2': 0.0, 'power_factor_3': 0.0, 'current_frequency': 49.97, 'total_energy_consumed': 8554.31, 'active_energy_import': 5393.05, 'active_energy_export': 3161.26}, 1)
2023-06-02 14:10:12.457 DEBUG (MainThread) [custom_components.hekr.hekr_data] Performing update on 6 entities for command "reportData"
2023-06-02 14:10:12.457 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hekr/hekr_data.py", line 186, in callback_update_entities
await asyncio.wait(tasks)
File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
2023-06-02 14:10:12.463 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.11/asyncio/base_events.py:1923: RuntimeWarning: coroutine 'HekrEntity.handle_data_update' was never awaited
handle = None # Needed to break cycles when an exception occurs.
2023-06-02 14:10:15.762 DEBUG (MainThread) [custom_components.hekr.hekr_data] Running update command: queryDev
2023-06-02 14:10:15.802 DEBUG (MainThread) [custom_components.hekr.hekr_data] Received response (message ID: 3) from information command (action: appSendResp) with data: (<Command("queryDev", 0, SEND)>, {}, 2)
2023-06-02 14:10:15.803 DEBUG (MainThread) [custom_components.hekr.hekr_data] No updates scheduled for command "queryDev"
2023-06-02 14:10:16.335 DEBUG (MainThread) [custom_components.hekr.hekr_data] Received response (message ID: 2286929) from information command (action: devSend) with data: (<Command("reportDev", 1, RECEIVE)>, {'phase_count': 1, 'switch_state': True, 'total_energy_consumed': 8554.32, 'warning_voltage': <VoltageWarning.OK: 0>, 'current_energy_consumption': -4.2276, 'warning_current': <CurrentWarning.OK: 0>, 'delay_timer': 0, 'delay_enabled': False, 'warning_battery': <PowerSupplyWarning.OK: 0>}, 1)
2023-06-02 14:10:16.335 DEBUG (MainThread) [custom_components.hekr.hekr_data] Performing update on 5 entities for command "reportDev"
2023-06-02 14:10:16.335 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hekr/hekr_data.py", line 186, in callback_update_entities
await asyncio.wait(tasks)
File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

**Comment by Telectroboy** [comment]
Closed by last update!
Thanks
