### ISSUE TITLE
Not working anymore after the update

### ISSUE THREAD

**Issue by michaelkaravani** [alryaz/hass-hekr-component#20]
According to the update everything was working fine now it doesn't even find the devices.

Local not working
And cloud doesn't work

1. I tried deleting and reinstalling.
2. I tried to configure via YAML
```
hekr:
  accounts:
    - username: !secret wisen_username
      password: !secret wisen_password
```
 

**in my HA log**
```
Logger: homeassistant.components.switch
Source: custom_components/hekr/base_platform.py:429
Integration: מתג (documentation, issues)
First occurred: 22:38:11 (1 occurrences)
Last logged: 22:38:11

Error while setting up hekr platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hekr/base_platform.py", line 429, in _async_setup_entry
    return all(await asyncio.wait(tasks))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

```

<img src="https://i.ibb.co/cNLmQx1/028.jpg" style="max-width: 100%;">

<img src="https://i.ibb.co/cxbkF62/029.jpg" style="max-width: 100%;">

<img src="https://i.ibb.co/DwfQT7N/030.jpg" style="max-width: 100%;">

**Comment by Telectroboy** [comment]
Are you really with the last version of HomeAssistant 2023.6 ??

**Comment by michaelkaravani** [comment]
<img src="https://i.ibb.co/xsP3H2y/031.jpg" style="max-width: 100%;">

**Comment by michaelkaravani** [comment]
I managed to fix it thanks
