### ISSUE TITLE
The integration is using deprecated constant "DEVICE_CLASS"

### ISSUE THREAD

**Issue by scannifn** [alryaz/hass-hekr-component#21]
These are multiple errors messages in HA registry:

DEVICE_CLASS_VOLTAGE was used from hekr, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.VOLTAGE instead, please report it to the author of the 'hekr' custom integration
ELECTRIC_CURRENT_AMPERE was used from hekr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please report it to the author of the 'hekr' custom integration
ELECTRIC_POTENTIAL_VOLT was used from hekr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'hekr' custom integration
ENERGY_KILO_WATT_HOUR was used from hekr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'hekr' custom integration
POWER_WATT was used from hekr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'hekr' custom integration
DEVICE_CLASS_SWITCH was used from hekr, this is a deprecated constant which will be removed in HA Core 2025.1. Use SwitchDeviceClass.SWITCH instead, please report it to the author of the 'hekr' custom integration

In addition:

HomeAssistantType was used from hekr, this is a deprecated alias which will be removed in HA Core 2025.5.
HomeAssistantType was used from hekr, this is a deprecated alias which will be removed in HA Core 2025.5.

**Comment by carmona15** [comment]
Additionally, I get this error:

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 1:40:43 PM (1 occurrences)
Last logged: 1:40:43 PM

Setup failed for custom integration 'hekr': Unable to import component: cannot import name 'ENERGY_KILO_WATT_HOUR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hekr/__init__.py", line 22, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/hekr/const.py", line 7, in <module>
    from homeassistant.const import (
    ...<7 lines>...
    )
ImportError: cannot import name 'ENERGY_KILO_WATT_HOUR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hekr/__init__.py", line 22, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/hekr/const.py", line 7, in <module>
    from homeassistant.const import (
    ...<7 lines>...
    )
ImportError: cannot import name 'ENERGY_KILO_WATT_HOUR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by scannifn** [comment]
Hello! I’ve installed the latest version of Home Assistant, 2025.1.0, and now the Hekr integration isn’t working anymore.

**Comment by iochtarasgmail** [comment]
Any idea if with core 2025.1.1 hekr is running

**Comment by Telectroboy** [comment]
> Any idea if with core 2025.1.1 hekr is running

I don't know, just rolled back to version 2024 for the moment

**Comment by iochtarasgmail** [comment]
Many thanks, since I don't have the knowledge how to rectify i also roll back to 2024.12 and I hope somebody with knowledge will rectify the issue. Many thanks

**Comment by iochtarasgmail** [comment]
Any idea or someone had any progress how to resolve the issue. Many thanks in advance!!

**Comment by scannifn** [comment]
I'm considering removing it from my Home Assistant server and replacing the product in the enclosure with a Shelly EM.
The author of this integration seems to have disappeared. I've been trying to contact them for the past 3-4 months without success.

**Comment by Telectroboy** [comment]
I didn't add time to start. It's a pity to change the hardware because of a software update issue. Especially it seems the only issue is the name of entities.

**Comment by iochtarasgmail** [comment]
It's a great device for me but since I don't have the knowledge to rectify integration, it seems that I will search for another device but not shelly. I had replaced many shelly 2.5 and 1 em due time capacitors. I will head to chinese solution.

**Comment by Telectroboy** [comment]
I will continue to look for a solution with this repository. And continue to learn how to do it. If you have logs to give, send them here. I'll try to understand. Maybe others will help too.

**Comment by iochtarasgmail** [comment]
Hope someone with knowledge will assist. I will try my best to figure out any solution. Many thanks in advance

**Comment by iochtarasgmail** [comment]
I tried yesterday with logs ri resolve the issue with the best of my knowledge but with out any success. Core was 2025.1.2 I rolled back to 2024.12

**Comment by iochtarasgmail** [comment]
good afternoon!! anybody with knowledge is trying to resolve the issue!!

**Comment by iochtarasgmail** [comment]
Everything is working again!! Many thanks for the kind assistance!!
